### ISSUE TITLE
Orientation field is not correctly serialized

### ISSUE THREAD

**Issue by goksel** [drdozer/shortbol#54]
The inline property for the above sequence annotation is not serialized correctly.
tetRInverter : DnaComponent
  sequenceAnnotation : at(pTetR,      1,   55, inline)

Current serialization: <test:inline rdf:resource="http://ico2s.org/inline"></icos:test>

It should be: <sbol:orientation rdf:resource="http://sbols.org/v2#inline"/>

**Comment by drdozer** [comment]
Can you double-check now? There was a buggy genomic.sbol file on sbolCommunity that was causing a range of interesting issues like this.

**Comment by goksel** [comment]
Fixed
