### ISSUE TITLE
RDF serialization of triples for resources should be updated

### ISSUE THREAD

**Issue by goksel** [drdozer/shortbol#55]
RDF triples for resources should be serialized with a slash at the end.
<sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"></sbol:type>

should be serialized as 

<sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>

**Comment by drdozer** [comment]
I agree. This is currently being handled by the underlying XML serialization library. The one used within the browser doesn't understand self-closing tags, mainly because various versions of various browsers do funkey things with self-closing tags. I'll look at how to improve this.

**Comment by goksel** [comment]
Closing this issue. The RDF is valid and the documents can be read by libSBOLj
