### ISSUE TITLE
MapsTo not local/remote not pointing to the functionalComponent

### ISSUE THREAD

**Issue by cjmyers** [drdozer/shortbol#64]
The id used for the componentDefinition for local and remote, it should be the generated id for the functionalComponent.

**Comment by drdozer** [comment]
Example please

**Comment by cjmyers** [comment]
Seems typos on my part.  The version below works.  Should not be permissive though.  If you give an id that is not a functionalComponent in the remote Module, it should flag an error.  Maybe this is related to the issue you were reporting earlier.

@import stdlib:sbol
@prefix tutorial <http://www.cbrc.kaust.edu.sa/sbolme/>
@defaultPrefix tutorial

ME_EC_2_3_1_74 : ProteinComponent
    name = "EC:2.3.1.74"
    description = "Chalcone synthase"
ME_EC_5_5_1_6 : ProteinComponent
ME_ath_AT5G13930 : ProteinComponent
ME_ath_AT3G55120 : ProteinComponent
ME_C00223 : SmallMoleculeComponent
    name = "p-Coumaroyl-CoA"
ME_C00083 : SmallMoleculeComponent
    name = "Malonyl-CoA"
ME_C00011 : SmallMoleculeComponent
    name = "CO2"
ME_C00010 : SmallMoleculeComponent
    name = "CoA"
ME_C06561 : SmallMoleculeComponent
    name = "Naringenin chalcone"
ME_C00509 : SmallMoleculeComponent
    name = "Naringenin"
enzyme : ProteinComponent

ME_R01613 : ModuleDefinition
    functionalComponent = ME_C00223
    functionalComponent = ME_C00083
    functionalComponent = ME_C00011
    functionalComponent = ME_C00010
    functionalComponent = enzyme

ME_R02446 : moduleDefinition
    functionalComponent = ME_C06561
    functionalComponent = ME_C00509
    functionalComponent = enzyme

abstracted_model : ModuleDefinition
    functionalComponent = ME_EC_2_3_1_74
    functionalComponent = ME_EC_5_5_1_6
    module : Module
        definition = ME_R01613
        name = "Chalcone synthase"
        mapsTo = ME_EC_2_3_1_74 replaces enzyme
    module : Module 
        definition = ME_R01613
        name = "Flavanone lyase"
        mapsTo = ME_EC_5_5_1_6 replaces enzyme

detailed_model : ModuleDefinition
    functionalComponent = ME_ath_AT5G13930
    functionalComponent = ME_ath_AT3G55120
    module : Module
        definition = abstracted_model
        mapsTo = ME_ath_AT5G13930 replaces ME_EC_2_3_1_74
        mapsTo = ME_ath_AT3G55120 replaces ME_EC_5_5_1_6

**Comment by drdozer** [comment]
This would be caught by a type-check phase. Closing. Started resurrecting the type-checker.
